import { escapeHTML as esc } from './engine.js';
const button = (text, attrs) => `<button type="button" ${attrs}>${text}</button>`;
export function renderRulesView(all, f, ruleId, form, d) {
  const rules = all.filter(r => (!f.category || (r.category ?? (r.kind === 'pattern' ? 'sentence' : 'word')) === f.category) && (!f.action || r.action === f.action) && (!f.search || [r.find, ...(r.values ?? [])].join(' ').toLowerCase().includes(f.search.toLowerCase())));
  const select = (key, choices) => `<select data-rule-filter="${key}" aria-label="${key === 'category' ? '按分类筛选' : '按处理方式筛选'}">${choices.map(([v, label]) => `<option value="${v}" ${f[key] === v ? 'selected' : ''}>${label}</option>`).join('')}</select>`;
  return `<div class="tr-bar"><span>${rules.length} / ${all.length} 条规则</span>${button('＋ 新建', 'data-action="new-rule"')}</div><div class="tr-rule-filters">${select('category', [['', '全部分类'], ['word', '字词'], ['sentence', '句式']])}${select('action', [['', '全部处理'], ['delete', '删除'], ['replace', '替换'], ['review', '仅提示']])}<input data-rule-filter="search" aria-label="搜索规则" placeholder="搜索识别或替换内容" value="${esc(f.search)}"></div>${bulkForm(d)}${ruleId === 'new' ? form() : ''}${[['word', '字词'], ['sentence', '句式']].map(([category, label]) => {
    const items = rules.filter(r => (r.category ?? (r.kind === 'pattern' ? 'sentence' : 'word')) === category);
    return items.length ? `<h3 class="tr-rule-heading">${label} · ${items.length}</h3>${items.map(r => `<section class="tr-rule-section"><div class="tr-rule-row">${button(`<span>${esc(r.find)}</span><span class="tr-meta">${r.kind === 'regex' ? '正则 · ' : ''}${{delete:'删除',replace:'替换',review:'仅提示'}[r.action]} · ${r.execution === 'auto' ? '自动' : '审阅'} ${ruleId === r.id ? '⌃' : '⌄'}</span>`, `class="tr-rule" data-rule="${esc(r.id)}" aria-expanded="${ruleId === r.id}"`)}<label class="tr-select"><input type="checkbox" data-rule-enabled="${esc(r.id)}" aria-label="启用规则：${esc(r.find)}" ${r.enabled !== false ? 'checked' : ''}></label></div>${ruleId === r.id ? form() : ''}</section>`).join('')}` : '';
  }).join('')}${!rules.length ? '<p class="tr-meta">没有符合筛选的规则。</p>' : ''}`;
}

function bulkForm(d) {
  const field = (key, label, choices) => `<label class="tr-field">${label}<select data-bulk-field="${key}">${choices.map(([v, name]) => `<option value="${v}" ${d[key] === v ? 'selected' : ''}>${name}</option>`).join('')}</select></label>`;
  return `<details class="tr-bulk"><summary>批量添加</summary><div class="tr-form-grid">${field('mode','匹配方式',[['text','普通文字 / {A} 句式'],['regex','正则']])}${field('action','处理方式',[['delete','删除'],['replace','替换'],['review','仅提示']])}${field('category','分类',[['word','字词'],['sentence','句式']])}${field('execution','何时应用',[['review','审阅后应用'],['auto','回复结束后自动应用']])}</div><p class="tr-meta">每行一条。删除或提示只填查找内容；替换用 Tab 分隔查找和替换，可从表格粘贴两列。含 | 的表达式仍是一条规则。</p><textarea data-bulk-field="text" aria-label="批量规则" rows="5" placeholder="死死地?">${esc(d.text)}</textarea><button type="button" data-action="bulk-add">添加这些规则</button></details>`;
}
